### ISSUE TITLE
Hello World! Plugin

### ISSUE THREAD

**Issue by fatflyingpigs** [powercord-community/suggestions#130]
**Describe the plugin**
A "Hello World!" plugin - it prints the classic noob friendly message "Hello World!"
This is aimed at new programmers and scripters that wish to participate in PowerCord.

**Expected behavior**
Several examples of how one might call the "Hello World!" message. This involves both:
1. the [User] input (button, context menu, starting program, changing guild/channel, command, etc.) and
2. the program's output (console.log, self user message, etc.)

**You can add other context, mockups or anything else here.**
no u

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by CodingKanin** [comment]
So is the idea of this just someone new picking up the request and making it or?

**Comment by KyzaGitHub** [comment]
This seems like something that the docs would cover rather than a plugin itself

**Comment by CodingKanin** [comment]
> This seems like something that the docs would cover rather than a plugin itself .

Yeah, im not sure what they're asking really. I mean it isn't against the guidelines but it's pretty pointless 🤔

**Comment by Bowser65** [comment]
As mentioned that'd be more of a documentation issue than an actual plugin request. There are plenty of plugins available in our #plugin-links channel, with all different purposes so they are already a great resource to get started as they cover a wide range of complexity, from easy to really advanced.

I know documentation are lacking but as of now I prefer focusing on user-facing features even if this sacrifices the developers, because there are more "normal" users than devs. While we can help developers in dev channels, the rapid growth of Powercord recently added quite a lot of work for the support team. But they will come! Eventually. Maybe.
