### ISSUE TITLE
Powercord Settings in Context Menu

### ISSUE THREAD

**Issue by xT3ll** [powercord-community/suggestions#132]
**Describe the plugin**
This plugin shows the Powercord settings in the context menu. Similar to [this](https://betterdiscordlibrary.com/plugins/BDContextMenu) BetterDiscord plugin

**Expected behavior**
Show the Powercord settings in config context menu

This plugin should be useful for fastly enabling and disabling other plugins and themes.
----

 - [X] I checked if this request wasn't already proposed
 - [X] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by Bowser65** [comment]
This is currently on our roadmap for Powercord Core

We currently have a lot planned for Powercord, and this is part of the idea behind the new API proposal I made back in September 2019 (powercord-org/powercord#231). It's not yet been worked on as it requires some work and time isn't a resource we (developers) have in large amounts. But it's planned! ~~There are even conspiracy theories saying that there's an experiment hidden in Powercord with this very feature. what a theory...~~

Since this is planned to be a core feature, I'll be closing the issue here in favor of the issue I've referenced above for tracking as this repository is more aimed for tracking third party plugins. Thanks for reaching out!
