### ISSUE TITLE
Word Counter: Show how many characters you have typed and characters left until the message won't send

### ISSUE THREAD

**Issue by BloodDragooner** [powercord-community/suggestions#140]
**Describe the plugin**
A plugin that shows total characters and warns the user in a red color when the message won't send.

**Expected behavior**
Show a word counter below the textarea to the right, and to show a red color to show when a message won't send after the user passed the character limit.

Already exists for BetterDiscord: https://betterdiscordlibrary.com/plugins/Char%20Counter
----

 - [yes] I checked if this request wasn't already proposed
 - [yes] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by thewilloftheshadow** [comment]
https://github.com/powercord-community/lettercount

**Comment by HooferDevelops** [comment]
> https://github.com/powercord-community/lettercount

does not work.

**Comment by Bowser65** [comment]
It has been discussed in Powercord's Discord server that this feature wouldn't be of a big use because Discord already provides this feature natively when you get close to the limit (200 chars remaining), which is more than enough to be aware of when you get close to the maximum 2k chars limit while typing.
