### ISSUE TITLE
Personal Pins Plugin

### ISSUE THREAD

**Issue by pythonmcpi** [powercord-community/suggestions#152]
### Description
A personal pins plugin (same functionality as the BetterDiscord one)

### More info
The BetterDiscord one has decided to stop working for me and I thought it would be nice to have a powercord plugin version. I also saw this idea suggested in the discord server by MulverineX#0001 (178551656714076161) but I didn't see another issue here with the same suggestion. As discussed on the discord this would simply store message links/cache messages but delete/edit the pins if the original message is added. (Also would delete the pin if server is gone) However if the user is offline/powercord is not loaded when the message edit/deletion is done then the pin may not get deleted. ~~Also, I would like to have an option for storing copies of the messages locally (obviously with a big popup warning about the dangers of it). If anyone thinks the last part breaks the Powercord plugin guidelines I'm willing to delete that part from the suggestion.~~ (Someone on the powercord discord said it breaks guidelines)

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by Swishilicous** [comment]
I've been working on this one for about a month but I can't make any promises that it'll ever release because school takes up a lot of my time.

**Comment by Swishilicous** [comment]
Actually, after reading the conversation that took place on 8/15 I wont be making this anymore. The whole reason I liked PersonalPins was because it was an easier way of screenshotting messages. The whole reason I use it is because it has this level of assurity that even if the message is deleted this important thing that I pinned wont be lost. For example something I would usually pin is a script someone sends in a server that way I can use it later. If that channel is deleted or the message is deleted I would want that to still be there. If the plugin doesn't save after deletion I'd rather just screenshot the message instead. 

I also don't get how it'd be breaking Discord API or whatever in the first place. All you'd be doing is writing the message contents to a text file.

**Comment by MulverineX** [comment]
Additional features that would be nice:
- Proper user component registered in the messages via storing the userid of the poster (left click to view their user dialog, right-click to get user tooltip menu)
- Server Linking; the server titles after the channel names of the noted messages should be clickable (+ bonus points if right-clicking opens the standard server tooltip menu)
- Option to disable server role color
- Option to disable server nickname (and display account name instead)

![image](https://user-images.githubusercontent.com/12068027/90370839-4986ad80-e02b-11ea-8fb4-ebc6cb8fa634.png)
Looks like it could potentially have the same functionality as the original. Need to get confirmation from the management discussion first though.

If this works out ^^^, other features:
- Optionally caching/displaying the user avatar. Since the save format isn't exactly needed to be human-readable you can probably just inline the Base64 strings of their avatars. (the alternative being caching the avatar link & if it goes dead fetching the updated one from their stored user id)
- Caching server name in case you leave the server or it's gone (and making it unclickable in that scenario)

**Comment by Bowser65** [comment]
Speaking officially this time: given the nature of the plugin, and the fact that it requires explicit user interaction to store the message, **we'll make an exception for this plugin and accept the plugin storing permanently messages**. Our Community Guidelines are a tool to fight abuse and keep our ecosystem ethical. This is a case of a fair-use of a message, so we'll consider it acceptable. *Note that this statement applies to **this** plugin request, and we do case-by-case reviews for plugins violating guidelines for "fair" reasons*.

Regarding the avatar caching, (or even the author' metadata) this isn't necessary. Discord has built-in methods that can be used to fetch a user's state from its ID (it'll fetch their name, discrim and avatar even if you don't have mutual servers). The up-to-date user can also already be in the internal users store, as it's likely the message author is a server member or someone you have an open DM channel with. In all cases, except if you attempt to fetch 150 different users at the same time, this should be relatively safe.

On another note, depending on how the Inline Reply experiment goes it might become standard for a native Discord client to fetch a single message, so "refreshing" a pinned message should be fairly easy.

**Comment by MulverineX** [comment]
I mentioned the author data caching because a lot of the time that can have some context to the message, and the user account could be since terminated.

**Comment by Swishilicous** [comment]
I'll take this. If anyone else wants to help me work on it they can DM me (as I suck with react so this might take a while).

**Comment by Swishilicous** [comment]
If anyone still wants to work on this I put the code on Github (https://github.com/Swishilicous/holy-notes).

**Comment by D-Brox** [comment]
I kinda got tired of waiting, so I decided to work a bit on Swishilicous code.
I added the delete note functionality, 'fixed' the problem with the note overlay in the modal, and added 3 useful commands. It currently works, but I'd still like to change a few things.
JS is not my language and I sucked at my attempts to work with React, and I don't have that much time because of college and work, so I can't make any promises. 
Code on [https://github.com/D-Brox/holy-notes](https://github.com/D-Brox/holy-notes)
If anyone else wants to help me work on it, please DM me.

**Comment by SammCheese** [comment]
^
With Help of D-Brox, I made the holy-notes plugin actually usable with the Modal.
There are a few things left to do but overall it works and doesnt look bad.

https://github.com/SammCheese/holy-notes

**Comment by D-Brox** [comment]
The plugin is completed and accessible in [https://github.com/D-Brox/holy-notes](https://github.com/D-Brox/holy-notes)

We are still fixing some small bugs that swoop under the radar, and we'll probably add some extra features suggested.
