### ISSUE TITLE
Better member list

### ISSUE THREAD

**Issue by Kanin** [powercord-community/suggestions#16]
### Description
Role names in the member list are centered, collapsable, and works with @Bowser65's "Role Color Everywhere" plugin to make the role name the color of said role. 

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by GriefMoDz** [comment]
I declare that this issue be claimed by me. Please and thank you. :raised_hands:

**Comment by CodingKanin** [comment]
Request is up for grabs again

**Comment by KyzaGitHub** [comment]
> collapsable

[This has been tried before.](https://cdn.discordapp.com/attachments/695590319810412615/715671432960409700/CollapsibleRoleHeaders.plugin.js) It worked, but not very well due to API limitations.

> you can remove and display elements all yo uwant
> but you can only request 900 members at a time
> (by breaking the limits)
> because by default it requests 0-99, then eg 200-299 and if on the edge of previous range, 300-399
> and now if you skip a bunch of members and you want some in 150 450 750 and 950, you're kinda screwed
> you can skip, but if you won't request a range of members to load, you won't see anything
![image](https://user-images.githubusercontent.com/40003440/87167391-e4f16980-c29a-11ea-850c-849eb5da87d8.png)
