### ISSUE TITLE
A button to can edit message's content locally (HERE'S AN IMAGE ABOUT HOW IT WOULD LOOK LIKE)

### ISSUE THREAD

**Issue by Camilo581** [powercord-community/suggestions#166]
hi there, well it's practically an inspect element shortcut (BUT OBVIOUSLY IT'S **LOCALLY**, IT WILL JUST CHANGE FOR US ETC xD)
![inspect_element_shortcut](https://user-images.githubusercontent.com/55998217/91620733-55099b00-e980-11ea-871d-0b2a51d325e8.png)

**Comment by Bowser65** [comment]
First of all, please follow the provided template for requesting plugins. We already have enough work and adapting requests is unnecessary wasted time.

Second, unlike editing someone's nickname locally, this doesn't have any util purpose. Editing someone's nickname locally can help quickly identifying someone often changing names and solve the problem of people with nicknames you can't type on a classical keyboard for mentioning them.

As of messages, there's simply no util purpose. Yes you could make memes with it, but overall making fake messages is a sketchy practice and can quickly result in severe abuse.

We don't want to facilitate abusive behaviors via Powercord, and since this plugin will most certainly be used mostly for the evil, we won't accept it.
