### ISSUE TITLE
Voice chat audio processing

### ISSUE THREAD

**Issue by D3XX3R** [powercord-community/suggestions#195]
### Description
Adds multiple audio processing layers to the voice chat audio

### More info
Adds noise gate, limiter, compressor and other audio effects to voice chat audio. I don't know if possible for input but it should be possible for voice output. That would make it a really enjoyable audio experience when you can filter out noisy microphones and screaming friends in voice chat.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by ADoesGit** [comment]
not *sure* if this is possible because it *seems* like audio is handled in the main thread, but I could be wrong

**Comment by MulverineX** [comment]
You could PR in an audio modulation API (allow routing audio stream through front-end process before being uploaded) into powercord core, if Bowser is alright with it.

**Comment by Bowser65** [comment]
It may be possible to catch and tamper with the audio in the renderer main world; however it'll most likely be super inefficient.

With the upcoming changes on what plugins do and what plugin can't do it might be a too low level plugin and it might not be achievable due to security concerns (plugins are treated as untrusted code and run isolated from the OS and native-level APIs).

If achievable, this will require additional APIs from Powercord; until we can define the technical constrains of this I'll leave it as pending review.

**Comment by ADoesGit** [comment]
upon further investigation there seems to be parts of the audio engine in the render that handle chat audio. I'll have to look later if there's a way to intercept the audio.

**Comment by D3XX3R** [comment]
This dead
