### ISSUE TITLE
Token Encrypt

### ISSUE THREAD

**Issue by leKamikaze1** [powercord-community/suggestions#304]
### Description
A plugin that encrypts your Discord Token with some sort of encryption like AES, and decrypts when needed

### More info
A practical use for this would be in the situation where you downloaded a virus that steals your discord token for malicious stuff, the token would be encrypted with, in this case, AES, the attacker would only receive the encrypted token, and wouldn't be able to decrypt it easily, since he would need to brute-force the secret key, which is very unlikely to happen

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by SomeAspy** [comment]
I think there would be a problem with this. as the client needs to send the unencrypted key for discord to actually use it, so the key has to be unencrypted before sending it anyway.

**Comment by leKamikaze1** [comment]
> I think there would be a problem with this. as the client needs to send the unencrypted key for discord to actually use it, so the key has to be unencrypted before sending it anyway.

That's why I said that it decrypts it when its needed, then, it encrypts it again

**Comment by SomeAspy** [comment]
Oh I see.

**Comment by TheOddGarlic** [comment]
I think they mean preventing apps from stealing them locally, but afaik apps that steal tokens just take the file that stores localStorage generated by Electron/Chromium, which means for this to be made;

1. Client shouldn't store tokens there and instead store them in an encrypted file.
2. Discord's own logic needs to be patched *a lot*  to instead use that.

Moreover, this isn't really useful as the token needs to be decrypted before being sent and (unless you want the user to enter the key every time they launch Discord) this means the encryption key will be stored locally, making this useless.

**Comment by cyyynthia** [comment]
Powercord plugins will no longer be able to interact with the token store due to security concerns in v3. Moreover, the token is queried by the client before plugins can interact and start patching.

This'd better be suited for an additional mod (like Powercord) responsible of this, since using this approach would let you directly do what you need to do in the main thread, you'd be able to capture way more reliably Discord being closed to encrypt the token, and you'd be able to pop a user-interface to request the password before Discord even ran its first lines of code (or at any moment you'd like). You'd even be able to only keep the token in memory and never write it somewhere at any given time, furthermore increasing the security of your token.

Keep in mind that, if you logged in Discord (or virtually anything) using any web browser, authorization tokens still exist on your computer, so this'd only be a guard against Discord-specific attacks. Better than nothing, but I just want to mention that.
