### ISSUE TITLE
Open Terminal Button

### ISSUE THREAD

**Issue by jeffboy70** [powercord-community/suggestions#307]
### Description
This plugin would add a button to the topbar that would open your default terminal application.

### More info
Would maybe work on Windows and MacOS too?

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by SomeAspy** [comment]
If you mean dev console, there is a shortcut for that. if you mean actual terminal, what is the point/use of integrating terminal? Your OS should handle things like shortcuts.

**Comment by jeffboy70** [comment]
I mean actual Terminal
I think it would be convenient, I spend a lot of time on discord.  It would be cool for there to be buttons in the topbar to open certain apps.

**Comment by cyyynthia** [comment]
Plugins will not be able to open random processes in v3 due to security concerns. It'll only be able to open apps which explicitly tells it's ok for third-parties to do so using custom protocols (like Spotify with the `spotify:` protocol). If you want a quick and easy way to fire up a terminal, you should use a keyboard shortcut like `Super+Enter`, or add a shortcut within your DE.
