### ISSUE TITLE
Auto clear cache

### ISSUE THREAD

**Issue by georgetzlp** [powercord-community/suggestions#313]
### Description
Auto clears discord's cache every X amount of time. Would also give a notification of when cache is cleared.

### More info
This would also have to fix the bug which makes you unable to switch channels after clearing its cache, of course.

----

 - [X] I checked if this request wasn't already proposed
 - [X] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by cyyynthia** [comment]
I'll assume that by cache you mean the info Discord stored in Flux stores (users, messages, etc..)

The problem of purging caches is that most data cannot be retrieved back from the gateway, due to Discord either not broadcasting the information because it knows your client is already supposed to have it (restrictions due to user-bot scraping prevention), or because the information is only sent during gateway init (guilds, and most of the channels data associated with guilds).

You'd either have to do a partial purge which would probably not be of a great interest, or purge everything and trigger a gateway reconnection *and* force the client to not initiate a RESUME (which would prevent the data you want to get back to be dispatched). If the point is to help with memory usage, I'd argue that a complete reload is way more effective, as you'd get rid of any leakage caused by Discord, a library used by Discord or a plugin, and you'd also be certain all the unnecessary data has been purged away safely and won't cause glitches.

**Comment by georgetzlp** [comment]
then maybe a plugin that gives a notification every x amount of time to tell you to reload discord? I'll make another issue with that.
