### ISSUE TITLE
Always show spotify invite option

### ISSUE THREAD

**Issue by KewlSage** [powercord-community/suggestions#314]
### Description
A plugin that would allow you to invite to listen from the upload button regardless of spotify status being enabled.
![upload button](https://user-images.githubusercontent.com/46802123/103438868-867bc700-4bfd-11eb-8e2b-fb300694cd1d.png)
### More info
nothing really too specific about it

----
 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by cyyynthia** [comment]
The problem is that Discord's implementation for Listening Along relies on the status to be enabled; It's from there that Discord knows what you're listening to and how Discord can synchronize playbacks. If your Spotify status is disabled, Discord doesn't have this information and is unable to let people listen along.

It'd require a plugin which broadcasts the information through an external server, and the plugin to be installed by everyone in order to function.

**Comment by KewlSage** [comment]
darn, thats not worth it, i'll just close this now.
