### ISSUE TITLE
Text React

### ISSUE THREAD

**Issue by mrrobboss** [powercord-community/suggestions#33]
**Describe the plugin**
Adds a command which reacts on the previous message with regional indicators.

**Expected behavior**
`.react bruh`
Reacts to the previous message with the emojis for b, r, u and h

 - [X] I checked if this request wasn't already proposed
 - [X] I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by Bowser65** [comment]
I'm unsure about a real utility that one, but why not. Discord said a couple times reactions aren't meant to be used this way, and we proved a couple times that reactions can get randomized pretty quickly. Since you can open the reaction picker and shift+click to add multiple reactions quickly a command to make it quicker can't do a lot of harm ig

**Comment by juby210-PL** [comment]
Claimed

**Comment by juby210-PL** [comment]
https://github.com/juby210-PL/text-react
