### ISSUE TITLE
Chat color codes

### ISSUE THREAD

**Issue by hwalker928** [powercord-community/suggestions#347]
### Description
A clear and concise description of what the plugin would do.
Don't get too specific, that's for the next part.
Add color codes for chat message, preferably using the Minecraft color system, so it converts &b to having a lightblue chat message, and they are also visible for anyone using the plugin.
### More info
You can here put more technical information, or get more specific.
Feel free to also add context, mockups or anything else here.
https://wiki.ess3.net/mc/

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by lzcunt** [comment]
Someone seeing "&b&kaaaaa&r &cJOIN MY ULTIMATE SERVER&r &b&kaaaaa&r" would be quite weird if they are not using the plugin. If someone does implement this, maybe instead of using Minecraft's text coloring, an actual markdown-like way of coloring would be better. As a side feature it could have more markdown features that are missing from Discord's markdown.

Also & is not Minecraft's coloring char, § is. In the Java Edition of the game, § can only be used in some configuration files, world names, books and server names. In Bedrock, it effects every text. & is just an alias for § added by a common server plugin, Essentials, which makes § and & also usable in the chat and user names. It is also considered legacy and is replaced by the Raw JSON Text Format.

**Comment by SomeAspy** [comment]
I imagine that the best way to do it might be by using zero width characters to store the color information.
