### ISSUE TITLE
Icon if there's a user note in chat area/member list

### ISSUE THREAD

**Issue by Vexed01** [powercord-community/suggestions#377]
### Description
Add a little icon next to users if you have a note for them, eg in the chat area and user list.

### More info
For my use I mean Discord's built-in note feature not one of the plugin ones but that could certainly be added (if possible) for other people, though not needed.

Something link this, but if possible with a single-colour icon or smth, not the notepad emoji. Exact positioning doesn't matter, just put it here as an example.
![sorry, images don't embed in discord](https://i.imgur.com/WR0yBFi.png)

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by cyyynthia** [comment]
This would most likely be problematic to implement because the client doesn't store anywhere if there's a note on someone or not, and instead just performs an API call everytime you look up someone's profile.

This means you'd need to send quite a lot of API requests to Discord - although the volume would be the same of the one generated by badges everywhere (and it's causing some problems)

**Comment by Vexed01** [comment]
This is a feature in the new https://github.com/GriefMoDz/notey plugin.
