### ISSUE TITLE
Better stream viewer 

### ISSUE THREAD

**Issue by AugustusUKR** [powercord-community/suggestions#383]
### Description
The plugin would allow you to change the resolution and fps of the steam you are watching, the same way you would control your own stream.

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by cyyynthia** [comment]
This is not achievable because Discord doesn't work like Twitch; they would need to reprocess the video stream on their end for users to be able to watch in different qualities and this is not something Discord is doing (because it'd be expensive for them in terms of hardware and it'd increase the latency).

The only way would be to re-encode locally which is just a waste of cpu since you already downloaded a higher quality video stream.
