### ISSUE TITLE
MessageLogger

### ISSUE THREAD

**Issue by LilSizzurp** [powercord-community/suggestions#39]
**Describe the plugin**
Should log deleted/edited messages like [MessageLogger](https://raw.githubusercontent.com/MessageLoggerBD/MessageLogger/master/MessageLogger.plugin.js).

**Expected behavior**
Helping server moderators detect ghost pings, bot abuse, etc. on their servers.
Would also help catching bot command expoiters like the current NotSoBot @everyone mention exploit.

----

 - [x] I checked if this request wasn't already proposed
 - ? I made sure this request follows Powercord's [plugin guidelines](https://github.com/powercord-community/guidelines)

**Comment by CodingKanin** [comment]
[Check out the Ghost Buster plugin](https://github.com/powercord-community/ghostbuster)

Anything beyond this I believe would fall under [Guideline #3](https://github.com/powercord-community/guidelines#3-no-circumvention-of-discord-permissions) correct @Bowser65?

**Comment by Bowser65** [comment]
Yes. Bots do get partial rights on the messages content due to their use of the official API through official ways. We don't get those rights, and therefore we aren't allowed to use others people data for those purposes (officially). We could ignore that and go on, but we decided to enforce Discord's Terms of Service to a certain extend to prevent potential abuse and keep the Powercord ecosystem ethical.

Ghost Buster plugin would fall into that category, but since it only logs messages in which you are pinged, we decided to accept its feature set as you can in some cases already know what was the message about (email/push notifications).

Even if that'd be in some cases useful, we won't be accepting such a plugin to be officially distributed due to its possible misuse and privacy concerns.
