### ISSUE TITLE
vzCompat

### ISSUE THREAD

**Issue by Aokiare** [powercord-community/suggestions#392]
### Description
a plugin to add a compatibility layer to vizality plugins. similar to bdCompat ~~and vz's pcCombat~~

### More info
plugin that makes vz plugins work on pc woo poggies

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by cyyynthia** [comment]
Vizality is a project in violation with the Porkord license terms and/or in violation with the contractual requirements set in place by the GNU GPL 3.0, depending on the maintainers opinion on which license terms should apply for code that has been published before May 31, 2020.

It will not receive any support from us and legal action is pending on that regard.

**Comment by bruhmomentoo** [comment]
![image](https://user-images.githubusercontent.com/10700329/111888074-5668e680-89ea-11eb-81d7-5dfa568a771c.png)
You cant just change a license then sue someone because they forked it before you changed the license.

**Comment by DanKGooGLy** [comment]
big chungus nutsack among sus

**Comment by bruhmomentoo** [comment]
# big chungus nutsack among sus

**Comment by cyyynthia** [comment]
The license text does not stop to the fields shown by choosealicense. As I mentioned, code published before May 31, 2020 may be under the terms of the GPL or Porkord as we effectively republished it under this license. However, the GNU GPL 3.0 does impose contractual requirements which forbid usage of the software as part of a larger, non-GPL compatible software. Powercord is effectively linking to Discord software which makes it, by contract, a single and unique program.

As such, use of GPL-licensed code to link to the Discord desktop application is not allowed. I can sue people because they violate my rights and their contractual obligations. I have locked this thread because the Vizality community proved yet again its maturity and its strong ability to talk with responsible adults.

![image](https://user-images.githubusercontent.com/9999055/111888407-801b1100-89dc-11eb-9aa2-9b59defe9df9.png)
