### ISSUE TITLE
Sort Member List's by role before sorting by offline

### ISSUE THREAD

**Issue by chyzman** [powercord-community/suggestions#442]
### Description
It would make it so offline users are still sorted under the roles they have instead of under the offline category

### More info
It would still grey out offline people but it would make it a lot easier to find out who is an admin even if they are offline

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by NyxIsBad** [comment]
It's worth noting servers stop showing offline members after a certain point (Any server above 1000 members) - im not sure if its still reasonable or doable to filter out the entire member list, but this could be technically difficult

**Comment by cyyynthia** [comment]
This is not possible because the client can't know the entire memberlist. It can only fetch from the api parts of the list, and discord engineered it specifically to work the way it is now. The way they've done it is very nice to have the member list load fast and not lag the fuck out of the client, but it means it's very not extensible and you're limited to what Discord designed the thing for.

**Comment by chyzman** [comment]
aren't u able to see what roles someone has? if so couldn't you find the highest role then put everyone with that role then second highest etc...?
