### ISSUE TITLE
plugin that filters bad words

### ISSUE THREAD

**Issue by ashy1227** [powercord-community/suggestions#447]
### Description
Hi,,,
curse words make me uncomfy but it's not really reasonable to get everyone to stop using them all the time so I just want a thingy that spoilers them or something

### More info
There's a plugin that already filters words but it blurs the whole message and also you have to put in the words an that also makes me uncomfy,,,

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by j0lol** [comment]
maybe make a request issue on that plugin?

**Comment by cyyynthia** [comment]
> There's a plugin that already filters words but it blurs the whole message
 
You should request to that plugin a feature to use spoilers (maybe a variant like a red-ish spoiler so they are distinguishable from real spoilers) rather than requesting a plugin that is 95% similar.

> you have to put in the words an that also makes me uncomfy

You are going to have to set things at some point, I really have no clue what you even expect here. However I can see how some words can cause discomfort and having a toggle to hide fields value once set could be a good enough compromise to me. Again something you should ask the original plugin author.
