### ISSUE TITLE
Upload images via slash commands

### ISSUE THREAD

**Issue by Hypertyrannical** [powercord-community/suggestions#456]
### Description
`/i imagename` uploads an image named `imagename` from a folder specified in the settings.

### More info
If multiple files match `imagename`, gifs are prioritized, then png, then jpg.

Perhaps non-images could be uploaded as well, but that could be a separate command that requires the extension as well, such as: `/u filename.zip`

Another possible feature could be to have text posted with the image (just as you can with a normal image upload), which would require a different syntax: `/i "imagename" Hey, check out this cool image!`

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by katlyn** [comment]
Note that such a plugin would use Powercord's command api, and not slash commands.

**Comment by 12944qwerty** [comment]
I made it :D https://github.com/12944qwerty/upload-commands

There is a small modification: Instead of prioritizing, there is a autofill so that you can choose the file you want.

Searches files based on the filepath in settings. I highly suggest you go update it as soon as you install this plugin. Default path is `C:\Users\user\Pictures`.

![preview](https://media.discordapp.net/attachments/755005584322854972/876661952586338344/upload_commands.gif?width=497&height=676)
