### ISSUE TITLE
Titlebar change

### ISSUE THREAD

**Issue by RinLovesYou** [powercord-community/suggestions#478]
### Description
I was wondering if it's possible to have a plugin that changes how the Titlebar behaves. Something like Chrome on Linux replacing the default titlebar.

### More info
This is already native in windows pretty much, but at least on linux it's not. I remember a BetterDiscord plugin that could emulate all OS types (linux/windows/mac). 

Basically i want this (please ignore the red markings)
![image](https://user-images.githubusercontent.com/29461788/121139858-82517680-c839-11eb-9965-848ea89ca013.png)
to replace this on Linux
![image](https://user-images.githubusercontent.com/29461788/121139919-972e0a00-c839-11eb-8c80-7db073eee868.png)

----

 - [x] I checked if this request wasn't already proposed
 - [x] I made sure this request follows Powercord's [plugin guidelines](https://powercord.dev/guidelines)

**Comment by arrrnmp** [comment]
What about people that use Window Managers, instead of Desktop Environments? In the Window Managers there is no title bar normally, as them tile the windows along the desktop. If I've understanded you correctly, you want to remove it, but that's inherit from your own Desktop Environment. So I think it couldn't be possible

**Comment by lzcunt** [comment]
A similar plugin exists. https://github.com/Litleck/custom-window-buttons

**Comment by RinLovesYou** [comment]
> A similar plugin exists. https://github.com/Litleck/custom-window-buttons

That is actually really close to what i want, so i'll close this suggestion. Tysm!
